name = "LibSerialPort"
uuid = "a05a14c7-6e3b-5ba9-90a2-45558833e1df"
version = "0.2.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "â‰¥ 0.7.0"
